export const ITEMS = [{
    id: "SillaCorsair",
    title: "Silla Corsair T3",
    detail: "La selección de una silla adecuada es muy importante para prevenir futuras lesiones. Con esta silla Corsair, vas a tener la comodidad y el bienestar que necesitás a lo largo de tu jornada",
    price: 75900,
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_798057-MLA43822611762_102020-O.webp",
    category: "sillas",
    stock: 10,
},
{
    id: "AurisLogitech",
    title: "Auriculares Logitech",
    detail: "Auris de virgo man no los compres o el momo te bannea",
    price: 17735,
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_798552-MLA44771577101_022021-O.webp",
    category: "auriculares",
    stock: 10,
},
{
    id: "MouseLogitech",
    title: "Mouse Logitech",
    detail: "G305 es un mouse inalámbrico para juegos LIGHTSPEED diseñado para un desempeño excelente con las innovaciones tecnológicas más recientes a un precio asequible.",
    price: 5600,
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_750649-MLA44091562174_112020-O.webp",
    category: "mouses",
    stock: 7,
}, {
    id: "SillaDxracer",
    title: "Silla Dxracer Origin Series",
    detail: "Diseñadas para aumentar la experiencia de juego, se convertirá en tu asiento preferido para trabajar y relajarte. De alta durabilidad y confort.",
    price: 76290,
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_943884-MLA45404177202_032021-O.webp",
    category: "sillas",
    stock: 5,
}, {
    id: "MouseRedragon",
    title: "Mouse Redragon M711",
    detail: "El mouse de juego te ofrecerá la posibilidad de marcar la diferencia y sacar ventajas en tus partidas. Su conectividad y sensor suave ayudará a que te desplaces rápido por la pantalla.",
    price: 3300,
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_812768-MLA32146214450_092019-O.webp",
    category: "mouses",
    stock: 10,
}, {
    id: "MouseHyperx",
    title: "Mouse HyperX Pulsefire Surge",
    detail: "Terrible mouse para sentar malardos en el cs mi rey",
    price: 4800,
    pictureUrl: "https://http2.mlstatic.com/D_NQ_NP_760141-MLA32146296703_092019-O.webp",
    category: "mouses",
    stock: 8,
},]